(defclass Event ()
   (  (Year :accessor Event-Year)
      (Month :accessor Event-Month)
      (Day :accessor Event-Day)
      (hour :accessor Event-hour)
      (Name :accessor Event-Name)
      (Notes :accessor Event-Notes)
   )
    )
    (defmethod timeUntil((object Event) currHour)
        (if(< (- (Event-Hour object) currHour) 0)
            (+ 24 (- (Event-Hour object) currHour))
            (- (Event-Hour object) currHour)))

    (defmethod getYear ((object Event))
        (format t "Year ~d~%" (Event-Year object))
    )

    (defmethod getHour ((object Event))
        (format t "Hour ~d~%" (Event-Hour object))
    )

    (defmethod getEvent ((object Event))
        (format t "Year: ~d~%" (Event-Year object))
        (format t "Month: ~d~%" (Event-Month object))
        (format t "Day: ~d~%" (Event-Day object))
        (format t "Hour: ~d~%" (Event-hour object))
        (format t "Name: ~d~%" (Event-Name object))
        (format t "Description/Notes: ~d~%" (Event-Notes object))
    )